# Site settings
title: ZenWave Code Generator
description: DDD and API-First Modeling Tools
github_username: ivangsa
# Theme settings
remote_theme: just-the-docs/just-the-docs
search_enabled: true
logo: 'https://avatars.githubusercontent.com/u/93670347'
aux_links:
  "See on GitHub":
    - "//github.com/zenwave360/zenwave-code-generator"
ga_tracking:  G-PWPE0ZF877
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)